# Generated by Django 5.0.6 on 2024-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_patrimony', models.CharField(db_index=True, max_length=20, verbose_name='N° Patrimonial')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ubicacíon')),
            ],
            options={
                'db_table': 'Patrimonio',
            },
        ),
    ]
