# Generated by Django 5.0.6 on 2024-07-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimony',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo'),
        ),
    ]
