# Generated by Django 5.0.6 on 2024-07-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_patrimony_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimony',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ubicacíon'),
        ),
    ]
