# Generated by Django 5.0.6 on 2024-06-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_remove_employee_asset_number_remove_employee_box_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_locker', models.CharField(blank=True, max_length=6, null=True, verbose_name='Numero de Taquilla')),
                ('status_locker', models.CharField(blank=True, choices=[('Reservado', 'Reservado'), ('Ocupado', 'Ocupado')], max_length=25, null=True, verbose_name='Estado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='employee.employee', verbose_name='Empleado')),
            ],
            options={
                'db_table': 'Taquillas',
            },
        ),
    ]
