# Generated by Django 5.0.6 on 2024-06-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='patrimony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.patrimony', verbose_name='Patrimonio'),
        ),
        migrations.AlterField(
            model_name='locker',
            name='status_locker',
            field=models.CharField(blank=True, choices=[('Reservado', 'Reservado'), ('Ocupado', 'Ocupado'), ('Libre', 'Libre')], max_length=25, null=True, verbose_name='Estado'),
        ),
    ]
