# Generated by Django 5.0.6 on 2024-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_asset_number_remove_employee_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('Monotributo', 'Monotributo'), ('Planta', 'Planta'), ('Planta Temporal', 'Planta Temporal'), ('Contratado', 'Contratado')], default='Planta', null=True, verbose_name='Sit. Laboral'),
        ),
    ]
