# Generated by Django 5.0.6 on 2024-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='condition',
            field=models.CharField(blank=True, default='N/A', null=True, verbose_name='Tiene Taquilla?'),
        ),
    ]
